version: "3.8"

services:
  mongo_db0:
    image: mongo:latest
    container_name: mongo_db0
    command: ["--replSet", "cherry", "--bind_ip_all", "--port", "30001"]
    volumes:
      - ./data/mongo-0:/data/db
    ports:
      - 30001:30001
    networks:
      - mongoCluster
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'cherry',members:[{_id:0,host:\"mongo_db0:30001\"},{_id:1,host:\"mongo_db1:30002\"},{_id:2,host:\"mongo_db2:30003\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongo_db1:
    image: mongo:latest
    container_name: mongo_db1
    command: ["--replSet", "cherry", "--bind_ip_all", "--port", "30002"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30002:30002
    networks:
      - mongoCluster

  mongo_db2:
    image: mongo:latest
    container_name: mongo_db2
    command: ["--replSet", "cherry", "--bind_ip_all", "--port", "30003"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30003:30003
    networks:
      - mongoCluster

networks:
  mongoCluster:
